sonar.projectKey=itinerfly
sonar.projectName=itinerfly
sonar.exclusions=src/tests/**,src/main.jsx,src/data/mockData.js
-Dsonar.sources=src \
-Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
