sonar.projectKey=jfk-itinerary-backend
sonar.projectName=jfk-itinerary-backend
sonar.sources=src
sonar.exclusions=src/mock/**, node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
